### ISSUE TITLE
Non-Local Usage

### ISSUE THREAD

**Issue by agahEbrahimi** [noffle/pubsub-swarm#3]
Hello,

Does this work with two different computers on two different networks? 

Thank you

**Comment by hackergrrl** [comment]
It ought to: it uses [discovery-swarm](https://github.com/mafintosh/discovery-swarm), which searches for peers both on the local network and online using the bittorrent [DHT](https://en.wikipedia.org/wiki/Distributed_hash_table).

**Comment by agahEbrahimi** [comment]
@noffle 
Hmm, it didn't work. 
Is there any specific thing I have to do to make it work with computers on two different networks?

**Comment by hackergrrl** [comment]
It's possible that there's a firewall or router in between your computers that
is causing the packets to get dropped. This is difficult to debug.
